export type DesignCategory = "investigation" | "promotional" | "review" | "editorial";

export interface DesignTheme {
  key: string;
  name: string;
  category: DesignCategory;
  preview: { bg: string; accent: string; text: string };
  styles: {
    pageBg: string;
    textColor: string;
    headingColor: string;
    accentColor: string;
    accentHover: string;
    cardBg: string;
    cardBorder: string;
    buttonStyle: string;
    heroOverlay: string;
    fontBody: string;
    fontHeading: string;
    glow?: string;
    pattern?: string;
  };
}

export const DESIGNS: DesignTheme[] = [
  // ═══════════════════════════════════════════════════════════════
  // INVESTIGATION — scam reports, fraud exposure, evidence pages
  // ═══════════════════════════════════════════════════════════════
  {
    key: "scam-alert",
    name: "Scam Alert",
    category: "investigation",
    preview: { bg: "#0a0000", accent: "#ef4444", text: "#d4d4d4" },
    styles: {
      pageBg: "bg-[#0a0000]",
      textColor: "text-gray-300",
      headingColor: "text-white",
      accentColor: "#ef4444",
      accentHover: "#dc2626",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#ef4444]/10",
      buttonStyle: "bg-gradient-to-r from-[#ef4444] to-[#dc2626] text-white font-bold hover:from-[#dc2626] hover:to-[#b91c1c] shadow-[0_0_30px_rgba(239,68,68,0.3)]",
      heroOverlay: "from-[#0a0000] via-[#0a0000]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
      glow: "shadow-[0_0_80px_rgba(239,68,68,0.08)]",
    },
  },
  {
    key: "fraud-radar",
    name: "Fraud Radar",
    category: "investigation",
    preview: { bg: "#0f0a00", accent: "#f97316", text: "#d4d4d4" },
    styles: {
      pageBg: "bg-[#0f0a00]",
      textColor: "text-gray-300",
      headingColor: "text-white",
      accentColor: "#f97316",
      accentHover: "#ea580c",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#f97316]/10",
      buttonStyle: "bg-gradient-to-r from-[#f97316] to-[#ea580c] text-white font-bold hover:from-[#ea580c] hover:to-[#c2410c] shadow-[0_0_30px_rgba(249,115,22,0.3)]",
      heroOverlay: "from-[#0f0a00] via-[#0f0a00]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
      glow: "shadow-[0_0_80px_rgba(249,115,22,0.08)]",
    },
  },
  {
    key: "cyber-forensic",
    name: "Cyber Forensic",
    category: "investigation",
    preview: { bg: "#000a00", accent: "#22c55e", text: "#86efac" },
    styles: {
      pageBg: "bg-[#000a00]",
      textColor: "text-green-300/70",
      headingColor: "text-green-100",
      accentColor: "#22c55e",
      accentHover: "#16a34a",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#22c55e]/10",
      buttonStyle: "bg-[#22c55e] text-black font-bold hover:bg-[#16a34a] shadow-[0_0_30px_rgba(34,197,94,0.35)]",
      heroOverlay: "from-[#000a00] via-[#000a00]/70 to-transparent",
      fontBody: "font-mono",
      fontHeading: "font-mono",
      glow: "shadow-[0_0_80px_rgba(34,197,94,0.06)]",
    },
  },
  {
    key: "dark-intel",
    name: "Dark Intel",
    category: "investigation",
    preview: { bg: "#0b0014", accent: "#a855f7", text: "#c4b5fd" },
    styles: {
      pageBg: "bg-[#0b0014]",
      textColor: "text-purple-200/70",
      headingColor: "text-white",
      accentColor: "#a855f7",
      accentHover: "#9333ea",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#a855f7]/10",
      buttonStyle: "bg-gradient-to-r from-[#a855f7] to-[#7c3aed] text-white font-bold hover:from-[#9333ea] hover:to-[#6d28d9] shadow-[0_0_30px_rgba(168,85,247,0.25)]",
      heroOverlay: "from-[#0b0014] via-[#0b0014]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
      glow: "shadow-[0_0_80px_rgba(168,85,247,0.07)]",
    },
  },
  {
    key: "exposure-white",
    name: "Exposure Report",
    category: "investigation",
    preview: { bg: "#f8f8f8", accent: "#dc2626", text: "#374151" },
    styles: {
      pageBg: "bg-[#f8f8f8]",
      textColor: "text-gray-700",
      headingColor: "text-gray-900",
      accentColor: "#dc2626",
      accentHover: "#b91c1c",
      cardBg: "bg-white/80 backdrop-blur",
      cardBorder: "border border-gray-200/60",
      buttonStyle: "bg-[#dc2626] text-white font-bold hover:bg-[#b91c1c]",
      heroOverlay: "from-[#f8f8f8] via-[#f8f8f8]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-serif",
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // PROMOTIONAL — brand showcase, product promo, sponsored content
  // ═══════════════════════════════════════════════════════════════
  {
    key: "luxe-gold",
    name: "Luxe Gold",
    category: "promotional",
    preview: { bg: "#0c0c0c", accent: "#d4a853", text: "#c9c9c9" },
    styles: {
      pageBg: "bg-[#0c0c0c]",
      textColor: "text-gray-400",
      headingColor: "text-white",
      accentColor: "#d4a853",
      accentHover: "#c49a45",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#d4a853]/10",
      buttonStyle: "bg-gradient-to-r from-[#d4a853] to-[#b8923e] text-black font-bold hover:from-[#e0b560] hover:to-[#c49a45]",
      heroOverlay: "from-[#0c0c0c] via-[#0c0c0c]/70 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-serif",
      glow: "shadow-[0_0_60px_rgba(212,168,83,0.06)]",
    },
  },
  {
    key: "fresh-gradient",
    name: "Fresh Modern",
    category: "promotional",
    preview: { bg: "#f0f4f8", accent: "#2563eb", text: "#334155" },
    styles: {
      pageBg: "bg-[#f0f4f8]",
      textColor: "text-slate-600",
      headingColor: "text-slate-900",
      accentColor: "#2563eb",
      accentHover: "#1d4ed8",
      cardBg: "bg-white/80 backdrop-blur",
      cardBorder: "border border-slate-200/60",
      buttonStyle: "bg-[#2563eb] text-white font-semibold hover:bg-[#1d4ed8]",
      heroOverlay: "from-[#f0f4f8] via-[#f0f4f8]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
    },
  },
  {
    key: "neon-promo",
    name: "Neon Promo",
    category: "promotional",
    preview: { bg: "#0d0015", accent: "#ff2d78", text: "#d0d0d0" },
    styles: {
      pageBg: "bg-[#0d0015]",
      textColor: "text-gray-300",
      headingColor: "text-white",
      accentColor: "#ff2d78",
      accentHover: "#e6266c",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#ff2d78]/10",
      buttonStyle: "bg-[#ff2d78] text-white font-bold hover:bg-[#e6266c] shadow-[0_0_30px_rgba(255,45,120,0.3)]",
      heroOverlay: "from-[#0d0015] via-[#0d0015]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
      glow: "shadow-[0_0_80px_rgba(255,45,120,0.07)]",
    },
  },
  {
    key: "clean-minimal",
    name: "Clean Minimal",
    category: "promotional",
    preview: { bg: "#fafafa", accent: "#18181b", text: "#52525b" },
    styles: {
      pageBg: "bg-[#fafafa]",
      textColor: "text-zinc-500",
      headingColor: "text-zinc-900",
      accentColor: "#18181b",
      accentHover: "#27272a",
      cardBg: "bg-white/80 backdrop-blur",
      cardBorder: "border border-zinc-200",
      buttonStyle: "bg-zinc-900 text-white font-semibold hover:bg-zinc-800",
      heroOverlay: "from-[#fafafa] via-[#fafafa]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
    },
  },
  {
    key: "bold-impact",
    name: "Bold Impact",
    category: "promotional",
    preview: { bg: "#020617", accent: "#3b82f6", text: "#94a3b8" },
    styles: {
      pageBg: "bg-[#020617]",
      textColor: "text-slate-400",
      headingColor: "text-white",
      accentColor: "#3b82f6",
      accentHover: "#2563eb",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#3b82f6]/10",
      buttonStyle: "bg-[#3b82f6] text-white font-bold hover:bg-[#2563eb] shadow-[0_0_30px_rgba(59,130,246,0.3)]",
      heroOverlay: "from-[#020617] via-[#020617]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
      glow: "shadow-[0_0_80px_rgba(59,130,246,0.07)]",
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // REVIEW — product reviews, analysis, comparisons, trust scores
  // ═══════════════════════════════════════════════════════════════
  {
    key: "tech-review",
    name: "Tech Review",
    category: "review",
    preview: { bg: "#0a0a0f", accent: "#06b6d4", text: "#94a3b8" },
    styles: {
      pageBg: "bg-[#0a0a0f]",
      textColor: "text-slate-400",
      headingColor: "text-white",
      accentColor: "#06b6d4",
      accentHover: "#0891b2",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#06b6d4]/10",
      buttonStyle: "bg-[#06b6d4] text-white font-bold hover:bg-[#0891b2] shadow-[0_0_24px_rgba(6,182,212,0.25)]",
      heroOverlay: "from-[#0a0a0f] via-[#0a0a0f]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
      glow: "shadow-[0_0_80px_rgba(6,182,212,0.06)]",
    },
  },
  {
    key: "verdict-green",
    name: "Verdict",
    category: "review",
    preview: { bg: "#f0fdf4", accent: "#16a34a", text: "#374151" },
    styles: {
      pageBg: "bg-[#f0fdf4]",
      textColor: "text-gray-700",
      headingColor: "text-gray-900",
      accentColor: "#16a34a",
      accentHover: "#15803d",
      cardBg: "bg-white/80 backdrop-blur",
      cardBorder: "border border-green-200/60",
      buttonStyle: "bg-[#16a34a] text-white font-semibold hover:bg-[#15803d]",
      heroOverlay: "from-[#f0fdf4] via-[#f0fdf4]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
    },
  },
  {
    key: "deep-analysis",
    name: "Deep Analysis",
    category: "review",
    preview: { bg: "#0f0806", accent: "#f97316", text: "#d4d4d4" },
    styles: {
      pageBg: "bg-[#0f0806]",
      textColor: "text-gray-400",
      headingColor: "text-white",
      accentColor: "#f97316",
      accentHover: "#ea580c",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#f97316]/10",
      buttonStyle: "bg-gradient-to-r from-[#f97316] to-[#dc2626] text-white font-bold hover:from-[#ea580c] hover:to-[#b91c1c]",
      heroOverlay: "from-[#0f0806] via-[#0f0806]/70 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
      glow: "shadow-[0_0_60px_rgba(249,115,22,0.06)]",
    },
  },
  {
    key: "trust-score",
    name: "Trust Score",
    category: "review",
    preview: { bg: "#f0fdfa", accent: "#0d9488", text: "#334155" },
    styles: {
      pageBg: "bg-[#f0fdfa]",
      textColor: "text-slate-600",
      headingColor: "text-slate-900",
      accentColor: "#0d9488",
      accentHover: "#0f766e",
      cardBg: "bg-white/80 backdrop-blur",
      cardBorder: "border border-teal-200/60",
      buttonStyle: "bg-[#0d9488] text-white font-semibold hover:bg-[#0f766e]",
      heroOverlay: "from-[#f0fdfa] via-[#f0fdfa]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
    },
  },
  {
    key: "compare-split",
    name: "Comparison",
    category: "review",
    preview: { bg: "#070020", accent: "#818cf8", text: "#a5b4fc" },
    styles: {
      pageBg: "bg-[#070020]",
      textColor: "text-indigo-200/60",
      headingColor: "text-white",
      accentColor: "#818cf8",
      accentHover: "#6366f1",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#818cf8]/10",
      buttonStyle: "bg-gradient-to-r from-[#818cf8] to-[#6366f1] text-white font-bold hover:from-[#6366f1] hover:to-[#4f46e5] shadow-[0_0_30px_rgba(129,140,248,0.2)]",
      heroOverlay: "from-[#070020] via-[#070020]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
      glow: "shadow-[0_0_80px_rgba(129,140,248,0.06)]",
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // EDITORIAL — press releases, case studies, corporate, data
  // ═══════════════════════════════════════════════════════════════
  {
    key: "press-navy",
    name: "Press Release",
    category: "editorial",
    preview: { bg: "#ffffff", accent: "#1e3a5f", text: "#475569" },
    styles: {
      pageBg: "bg-white",
      textColor: "text-slate-500",
      headingColor: "text-slate-900",
      accentColor: "#1e3a5f",
      accentHover: "#172e4a",
      cardBg: "bg-white/80 backdrop-blur",
      cardBorder: "border border-slate-200",
      buttonStyle: "bg-[#1e3a5f] text-white font-semibold hover:bg-[#172e4a]",
      heroOverlay: "from-white via-white/70 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-serif",
    },
  },
  {
    key: "case-study",
    name: "Case Study",
    category: "editorial",
    preview: { bg: "#f8fafc", accent: "#0ea5e9", text: "#475569" },
    styles: {
      pageBg: "bg-[#f8fafc]",
      textColor: "text-slate-500",
      headingColor: "text-slate-900",
      accentColor: "#0ea5e9",
      accentHover: "#0284c7",
      cardBg: "bg-white/80 backdrop-blur",
      cardBorder: "border border-sky-100",
      buttonStyle: "bg-[#0ea5e9] text-white font-semibold hover:bg-[#0284c7]",
      heroOverlay: "from-[#f8fafc] via-[#f8fafc]/70 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
    },
  },
  {
    key: "annual-report",
    name: "Annual Report",
    category: "editorial",
    preview: { bg: "#fffbeb", accent: "#92400e", text: "#78716c" },
    styles: {
      pageBg: "bg-[#fffbeb]",
      textColor: "text-stone-500",
      headingColor: "text-stone-900",
      accentColor: "#92400e",
      accentHover: "#78350f",
      cardBg: "bg-white/80 backdrop-blur",
      cardBorder: "border border-amber-200/60",
      buttonStyle: "bg-[#92400e] text-white font-semibold hover:bg-[#78350f]",
      heroOverlay: "from-[#fffbeb] via-[#fffbeb]/60 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-serif",
    },
  },
  {
    key: "creative-studio",
    name: "Creative Studio",
    category: "editorial",
    preview: { bg: "#1a0a1e", accent: "#f43f5e", text: "#fda4af" },
    styles: {
      pageBg: "bg-gradient-to-br from-[#1a0a1e] via-[#1a0510] to-[#0f0a1e]",
      textColor: "text-rose-200/60",
      headingColor: "text-white",
      accentColor: "#f43f5e",
      accentHover: "#e11d48",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#f43f5e]/10",
      buttonStyle: "bg-gradient-to-r from-[#f43f5e] to-[#f97316] text-white font-bold hover:from-[#e11d48] hover:to-[#ea580c]",
      heroOverlay: "from-[#1a0a1e] via-[#1a0510]/70 to-transparent",
      fontBody: "font-sans",
      fontHeading: "font-sans",
      glow: "shadow-[0_0_80px_rgba(244,63,94,0.06)]",
    },
  },
  {
    key: "data-driven",
    name: "Data Driven",
    category: "editorial",
    preview: { bg: "#020210", accent: "#00f0ff", text: "#a5f3fc" },
    styles: {
      pageBg: "bg-[#020210]",
      textColor: "text-cyan-200/50",
      headingColor: "text-white",
      accentColor: "#00f0ff",
      accentHover: "#00d4e0",
      cardBg: "bg-white/[0.03] backdrop-blur-xl",
      cardBorder: "border border-[#00f0ff]/10",
      buttonStyle: "bg-[#00f0ff] text-black font-bold hover:bg-[#00d4e0] shadow-[0_0_30px_rgba(0,240,255,0.3)]",
      heroOverlay: "from-[#020210] via-[#020210]/60 to-transparent",
      fontBody: "font-mono",
      fontHeading: "font-sans",
      glow: "shadow-[0_0_80px_rgba(0,240,255,0.06)]",
    },
  },
];

export function getDesign(key: string): DesignTheme {
  return DESIGNS.find((d) => d.key === key) || DESIGNS[0];
}
